name: dream_home
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  dartz: ^0.10.1
  get_it: ^8.0.3
  shared_preferences: ^2.3.4
  fluttertoast: ^8.2.10
  lottie: ^3.3.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/vectors/
    - assets/images/anim/

  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Black.ttf
        - asset: assets/fonts/PublicSans-BlackItalic.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-BoldItalic.ttf
        - asset: assets/fonts/PublicSans-ExtraBold.ttf
        - asset: assets/fonts/PublicSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PublicSans-ExtraLight.ttf
        - asset: assets/fonts/PublicSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PublicSans-Italic.ttf
        - asset: assets/fonts/PublicSans-Light.ttf
        - asset: assets/fonts/PublicSans-LightItalic.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-MediumItalic.ttf
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
        - asset: assets/fonts/PublicSans-SemiBoldItalic.ttf
        - asset: assets/fonts/PublicSans-Thin.ttf
        - asset: assets/fonts/PublicSans-ThinItalic.ttf

